import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import { auth } from "@/auth";
import { redirect } from "next/navigation";
import { Toaster } from "@/components/ui/sonner";
import { EdgeStoreProvider } from "@/lib/edgestore";
import {DndContext} from '@dnd-kit/core';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "socialite.",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  if (!session?.user) {
    redirect("/api/auth/signin?callbackUrl=/");
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <EdgeStoreProvider>
          <Header user={session?.user} />
          {children}

          <Toaster />
        </EdgeStoreProvider>

      </body>
    </html>
  );
}
