import { auth } from "@/auth";
import { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Submit to socialite.",
  description: "Generated by create next app",
};
export default async function SubmitLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    const session = await auth();
    if (!session?.user) {
      redirect("/api/auth/signin?callbackUrl=/");
    }
    return (
      <>
          {children}
          
      </>
    );
  }
  